# Generated by Django 5.2.7 on 2025-10-14 09:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_day', models.PositiveIntegerField(help_text='День месяца оплаты')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='debts.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('claim', 'Досудебная претензия')], max_length=20)),
                ('sent_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debts.tenant')),
            ],
        ),
    ]
